#!/usr/bin/python3
import socket
import sys
from _thread import *
import select 
import re

if len(sys.argv)!=2:
    print("Input format be = ./chatserver ip:port ")
    sys.exit()

my_server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
my_server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)


my_info = (sys.argv[1])
a=Info.split(':')
my_ip_addr=str(a[0])
my_port=int(a[1])